2024-03-30 12:27:04,743 INFO Watching for file changes with StatReloader
2024-03-30 12:27:12,307 WARNING Bad Request: /api/add_stats/
2024-03-30 12:27:25,111 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:27:26,051 INFO Watching for file changes with StatReloader
2024-03-30 12:27:34,663 WARNING Bad Request: /api/add_stats/
2024-03-30 12:28:27,791 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:28:28,730 INFO Watching for file changes with StatReloader
2024-03-30 12:29:07,278 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:29:08,156 INFO Watching for file changes with StatReloader
2024-03-30 12:29:16,018 ERROR Internal Server Error: /api/add_stats/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 28, in add_stats
    manga = Manga.objects.get(pk=request.POST.get('manga', None))
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
manga.models.Manga.DoesNotExist: Manga matching query does not exist.
2024-03-30 12:29:36,865 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:29:37,786 INFO Watching for file changes with StatReloader
2024-03-30 12:29:44,668 WARNING Not Found: /api/add_stats/
2024-03-30 12:30:06,934 WARNING Not Found: /api/add_stats/
2024-03-30 12:30:22,174 WARNING Bad Request: /api/add_stats/
2024-03-30 12:30:27,445 WARNING Bad Request: /api/add_stats/
2024-03-30 12:31:05,588 WARNING Bad Request: /api/add_stats/
2024-03-30 12:31:08,408 WARNING Bad Request: /api/add_stats/
2024-03-30 12:32:21,183 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:32:22,065 INFO Watching for file changes with StatReloader
2024-03-30 12:32:25,551 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:32:26,422 INFO Watching for file changes with StatReloader
2024-03-30 12:32:52,746 ERROR Internal Server Error: /api/add_stats/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 30, in add_stats
    data_jsonn = json.loads(request.POST)
  File "C:\Users\Shamrock\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not QueryDict
2024-03-30 12:33:15,532 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:33:16,594 INFO Watching for file changes with StatReloader
2024-03-30 12:33:33,714 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:33:34,689 INFO Watching for file changes with StatReloader
2024-03-30 12:33:42,180 WARNING Bad Request: /api/add_stats/
2024-03-30 12:34:37,084 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:34:37,986 INFO Watching for file changes with StatReloader
2024-03-30 12:34:52,630 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:34:53,617 INFO Watching for file changes with StatReloader
2024-03-30 12:35:18,257 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:35:19,259 INFO Watching for file changes with StatReloader
2024-03-30 12:35:27,031 WARNING Bad Request: /api/add_stats/
2024-03-30 12:35:41,841 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:35:42,756 INFO Watching for file changes with StatReloader
2024-03-30 12:37:36,653 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:37:37,553 INFO Watching for file changes with StatReloader
2024-03-30 12:37:51,368 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:37:52,366 INFO Watching for file changes with StatReloader
2024-03-30 12:38:01,014 ERROR Internal Server Error: /api/add_stats/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\annoying\fields.py", line 36, in __get__
    .__get__(instance, instance_type)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
manga.models.Manga.stats.RelatedObjectDoesNotExist: Manga has no stats.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
manga.models.Stats.DoesNotExist: Stats matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'bookmarks' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 35, in add_stats
    if manga.stats.rating is None or manga.stats.bookmarks is None: # type: ignore
  File "C:\Users\Shamrock\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\annoying\fields.py", line 40, in __get__
    obj, _ = model.objects.get_or_create(**{self.related.field.name: instance})
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 955, in get_or_create
    return self.create(**params), True
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'bookmarks' cannot be null")
2024-03-30 12:38:24,380 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:38:25,390 INFO Watching for file changes with StatReloader
2024-03-30 12:38:30,200 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:38:31,279 INFO Watching for file changes with StatReloader
2024-03-30 12:38:39,103 ERROR Internal Server Error: /api/add_stats/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\annoying\fields.py", line 36, in __get__
    .__get__(instance, instance_type)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
manga.models.Manga.stats.RelatedObjectDoesNotExist: Manga has no stats.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
manga.models.Stats.DoesNotExist: Stats matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'bookmarks' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 36, in add_stats
    if manga.stats.rating is None or manga.stats.bookmarks is None: # type: ignore
  File "C:\Users\Shamrock\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\annoying\fields.py", line 40, in __get__
    obj, _ = model.objects.get_or_create(**{self.related.field.name: instance})
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 955, in get_or_create
    return self.create(**params), True
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'bookmarks' cannot be null")
2024-03-30 12:39:15,382 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:39:16,252 INFO Watching for file changes with StatReloader
2024-03-30 12:39:43,237 ERROR Internal Server Error: /api/add_stats/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\annoying\fields.py", line 36, in __get__
    .__get__(instance, instance_type)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
manga.models.Manga.stats.RelatedObjectDoesNotExist: Manga has no stats.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
manga.models.Stats.DoesNotExist: Stats matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'bookmarks' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 36, in add_stats
    if manga.stats.exists():
  File "C:\Users\Shamrock\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\annoying\fields.py", line 40, in __get__
    obj, _ = model.objects.get_or_create(**{self.related.field.name: instance})
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 955, in get_or_create
    return self.create(**params), True
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'bookmarks' cannot be null")
2024-03-30 12:40:21,863 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 12:40:22,963 INFO Watching for file changes with StatReloader
2024-03-30 12:40:51,539 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 12:40:53,284 INFO Watching for file changes with StatReloader
2024-03-30 12:41:24,353 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:41:25,659 INFO Watching for file changes with StatReloader
2024-03-30 12:41:33,532 ERROR Internal Server Error: /api/add_stats/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry '706' for key 'manga_stats.PRIMARY'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 36, in add_stats
    serializer.save()
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '706' for key 'manga_stats.PRIMARY'")
2024-03-30 12:41:50,319 WARNING Bad Request: /api/add_stats/
2024-03-30 12:41:59,878 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:42:00,928 INFO Watching for file changes with StatReloader
2024-03-30 12:42:18,767 WARNING Bad Request: /api/add_stats/
2024-03-30 12:42:30,752 WARNING Bad Request: /api/add_stats/
2024-03-30 12:42:56,251 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:42:57,157 INFO Watching for file changes with StatReloader
2024-03-30 12:43:06,175 WARNING Bad Request: /api/add_stats/
2024-03-30 12:43:12,460 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:43:13,583 INFO Watching for file changes with StatReloader
2024-03-30 12:43:23,754 WARNING Bad Request: /api/add_stats/
2024-03-30 12:43:59,615 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:44:00,770 INFO Watching for file changes with StatReloader
2024-03-30 12:44:16,602 WARNING Bad Request: /api/add_stats/
2024-03-30 12:48:18,832 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:48:19,729 INFO Watching for file changes with StatReloader
2024-03-30 12:48:40,162 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:48:41,031 INFO Watching for file changes with StatReloader
2024-03-30 12:48:51,337 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:48:52,145 INFO Watching for file changes with StatReloader
2024-03-30 12:49:00,603 WARNING Bad Request: /api/add_stats/
2024-03-30 12:49:09,463 WARNING Bad Request: /api/add_stats/
2024-03-30 12:50:09,064 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:50:10,171 INFO Watching for file changes with StatReloader
2024-03-30 12:50:18,560 WARNING Bad Request: /api/add_stats/
2024-03-30 12:51:41,482 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:51:42,330 INFO Watching for file changes with StatReloader
2024-03-30 12:51:46,020 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:51:46,880 INFO Watching for file changes with StatReloader
2024-03-30 12:52:58,641 WARNING Bad Request: /api/add_stats/
2024-03-30 12:54:03,749 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\serializers.py changed, reloading.
2024-03-30 12:54:04,577 INFO Watching for file changes with StatReloader
2024-03-30 12:54:06,920 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\serializers.py changed, reloading.
2024-03-30 12:54:07,820 INFO Watching for file changes with StatReloader
2024-03-30 12:54:12,784 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\serializers.py changed, reloading.
2024-03-30 12:54:13,709 INFO Watching for file changes with StatReloader
2024-03-30 12:54:30,932 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:54:31,826 INFO Watching for file changes with StatReloader
2024-03-30 12:54:43,345 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:54:44,507 INFO Watching for file changes with StatReloader
2024-03-30 12:55:24,635 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:55:25,516 INFO Watching for file changes with StatReloader
2024-03-30 12:55:29,921 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:55:30,690 INFO Watching for file changes with StatReloader
2024-03-30 12:55:52,076 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:55:52,894 INFO Watching for file changes with StatReloader
2024-03-30 12:55:58,547 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:55:59,323 INFO Watching for file changes with StatReloader
2024-03-30 12:59:33,377 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 12:59:34,238 INFO Watching for file changes with StatReloader
2024-03-30 12:59:44,174 ERROR Internal Server Error: /api/add_stats/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'manga_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 35, in add_stats
    stats_instance = serializer.save()  # Сохраняем статистику
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'manga_id' cannot be null")
2024-03-30 13:00:56,011 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:00:56,880 INFO Watching for file changes with StatReloader
2024-03-30 13:01:07,452 ERROR Internal Server Error: /api/add_stats/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry '2262' for key 'manga_stats.PRIMARY'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 35, in add_stats
    stats_instance = serializer.save(manga=manga)  # Устанавливаем связь с мангой и сохраняем статистику
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '2262' for key 'manga_stats.PRIMARY'")
2024-03-30 13:04:32,357 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:04:33,189 INFO Watching for file changes with StatReloader
2024-03-30 13:05:07,709 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:05:08,530 INFO Watching for file changes with StatReloader
2024-03-30 13:05:19,792 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:05:20,617 INFO Watching for file changes with StatReloader
2024-03-30 13:05:22,948 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:05:23,832 INFO Watching for file changes with StatReloader
2024-03-30 13:05:29,471 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:05:30,263 INFO Watching for file changes with StatReloader
2024-03-30 13:05:53,212 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:05:54,057 INFO Watching for file changes with StatReloader
2024-03-30 13:06:06,788 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:06:07,647 INFO Watching for file changes with StatReloader
2024-03-30 13:07:07,654 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:07:08,579 INFO Watching for file changes with StatReloader
2024-03-30 13:07:19,132 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:07:19,906 INFO Watching for file changes with StatReloader
2024-03-30 13:08:27,265 ERROR Internal Server Error: /api/add_stats/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 506, in __get__
    rel_obj = self.related.get_cached_value(instance)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\fields\mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'stats'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'manga_stats.last_update' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 34, in add_stats
    if manga.stats.rating is None or manga.stats.bookmarks is None: # type: ignore
  File "C:\Users\Shamrock\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\annoying\fields.py", line 36, in __get__
    .__get__(instance, instance_type)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 514, in __get__
    rel_obj = self.get_queryset(instance=instance).get(**filter_args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\MySQLdb\connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'manga_stats.last_update' in 'field list'")
2024-03-30 13:12:23,741 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:12:24,697 INFO Watching for file changes with StatReloader
2024-03-30 13:13:00,931 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:13:01,930 INFO Watching for file changes with StatReloader
2024-03-30 13:13:18,983 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 13:13:20,041 INFO Watching for file changes with StatReloader
2024-03-30 13:13:30,071 ERROR Internal Server Error: /api/search/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\renderers.py", line 158, in render
    template_names = self.get_template_names(response, view)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\renderers.py", line 186, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Returned a template response with no `template_name` attribute set on either the view or response
2024-03-30 13:13:48,382 DEBUG Using proactor: IocpProactor
2024-03-30 13:13:54,497 DEBUG Using proactor: IocpProactor
2024-03-30 13:13:59,064 DEBUG Using proactor: IocpProactor
2024-03-30 13:14:02,943 DEBUG Using proactor: IocpProactor
2024-03-30 13:16:56,140 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:16:56,955 INFO Watching for file changes with StatReloader
2024-03-30 13:17:06,062 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:17:06,940 INFO Watching for file changes with StatReloader
2024-03-30 13:17:13,482 DEBUG Using proactor: IocpProactor
2024-03-30 13:17:19,711 DEBUG Using proactor: IocpProactor
2024-03-30 13:17:36,565 DEBUG Using proactor: IocpProactor
2024-03-30 13:17:38,817 DEBUG Using proactor: IocpProactor
2024-03-30 13:17:43,345 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:17:44,412 INFO Watching for file changes with StatReloader
2024-03-30 13:18:01,604 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:18:02,421 INFO Watching for file changes with StatReloader
2024-03-30 13:40:24,144 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:40:24,946 INFO Watching for file changes with StatReloader
2024-03-30 13:41:20,573 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:41:21,374 INFO Watching for file changes with StatReloader
2024-03-30 13:42:55,386 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:42:56,096 INFO Watching for file changes with StatReloader
2024-03-30 13:43:16,079 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:43:16,734 INFO Watching for file changes with StatReloader
2024-03-30 13:44:31,499 DEBUG Using proactor: IocpProactor
2024-03-30 13:44:38,329 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:44:39,489 INFO Watching for file changes with StatReloader
2024-03-30 13:44:43,518 DEBUG Using proactor: IocpProactor
2024-03-30 13:44:44,655 DEBUG Using proactor: IocpProactor
2024-03-30 13:44:50,716 DEBUG Using proactor: IocpProactor
2024-03-30 13:44:57,632 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:44:58,421 INFO Watching for file changes with StatReloader
2024-03-30 13:45:08,533 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:45:09,457 INFO Watching for file changes with StatReloader
2024-03-30 13:45:52,580 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:45:53,478 INFO Watching for file changes with StatReloader
2024-03-30 13:46:01,324 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:46:02,176 INFO Watching for file changes with StatReloader
2024-03-30 13:46:09,046 DEBUG Using proactor: IocpProactor
2024-03-30 13:46:18,215 DEBUG Using proactor: IocpProactor
2024-03-30 13:46:33,796 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:46:34,840 INFO Watching for file changes with StatReloader
2024-03-30 13:47:45,029 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:47:46,055 INFO Watching for file changes with StatReloader
2024-03-30 13:47:52,937 DEBUG Using proactor: IocpProactor
2024-03-30 13:48:18,912 DEBUG Using proactor: IocpProactor
2024-03-30 13:50:30,842 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:50:32,257 INFO Watching for file changes with StatReloader
2024-03-30 13:50:57,885 DEBUG Using proactor: IocpProactor
2024-03-30 13:51:02,431 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:51:03,782 INFO Watching for file changes with StatReloader
2024-03-30 13:51:19,124 DEBUG Using proactor: IocpProactor
2024-03-30 13:52:16,911 DEBUG Using proactor: IocpProactor
2024-03-30 13:52:42,591 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:52:43,508 INFO Watching for file changes with StatReloader
2024-03-30 13:53:06,166 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:53:07,231 INFO Watching for file changes with StatReloader
2024-03-30 13:53:26,921 DEBUG Using proactor: IocpProactor
2024-03-30 13:53:35,099 DEBUG Using proactor: IocpProactor
2024-03-30 13:53:37,109 DEBUG Using proactor: IocpProactor
2024-03-30 13:53:43,454 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:53:44,560 INFO Watching for file changes with StatReloader
2024-03-30 13:54:34,552 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:54:35,439 INFO Watching for file changes with StatReloader
2024-03-30 13:54:48,073 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:54:49,074 INFO Watching for file changes with StatReloader
2024-03-30 13:55:08,537 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:55:09,478 INFO Watching for file changes with StatReloader
2024-03-30 13:55:34,175 DEBUG Using proactor: IocpProactor
2024-03-30 13:56:13,565 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:56:14,474 INFO Watching for file changes with StatReloader
2024-03-30 13:56:38,203 DEBUG Using proactor: IocpProactor
2024-03-30 13:57:14,682 DEBUG Using proactor: IocpProactor
2024-03-30 13:57:35,322 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:57:36,320 INFO Watching for file changes with StatReloader
2024-03-30 13:57:51,847 DEBUG Using proactor: IocpProactor
2024-03-30 13:58:35,650 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:58:36,434 INFO Watching for file changes with StatReloader
2024-03-30 13:58:47,837 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:58:48,723 INFO Watching for file changes with StatReloader
2024-03-30 13:58:51,381 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:58:52,342 INFO Watching for file changes with StatReloader
2024-03-30 13:58:56,102 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 13:58:56,930 INFO Watching for file changes with StatReloader
2024-03-30 13:59:15,634 DEBUG Using proactor: IocpProactor
2024-03-30 14:00:13,275 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:00:14,440 INFO Watching for file changes with StatReloader
2024-03-30 14:00:37,222 DEBUG Using proactor: IocpProactor
2024-03-30 14:01:20,556 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:01:21,419 INFO Watching for file changes with StatReloader
2024-03-30 14:01:42,604 DEBUG Using proactor: IocpProactor
2024-03-30 14:02:03,187 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:02:04,012 INFO Watching for file changes with StatReloader
2024-03-30 14:02:27,802 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:02:28,659 INFO Watching for file changes with StatReloader
2024-03-30 14:02:31,289 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:02:32,137 INFO Watching for file changes with StatReloader
2024-03-30 14:02:47,446 DEBUG Using proactor: IocpProactor
2024-03-30 14:02:57,774 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:02:58,719 INFO Watching for file changes with StatReloader
2024-03-30 14:03:41,729 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:03:42,686 INFO Watching for file changes with StatReloader
2024-03-30 14:04:04,520 DEBUG Using proactor: IocpProactor
2024-03-30 14:05:55,922 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:05:57,085 INFO Watching for file changes with StatReloader
2024-03-30 14:06:21,397 DEBUG Using proactor: IocpProactor
2024-03-30 14:06:30,428 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:06:31,314 INFO Watching for file changes with StatReloader
2024-03-30 14:07:01,165 DEBUG Using proactor: IocpProactor
2024-03-30 14:07:33,449 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:07:34,592 INFO Watching for file changes with StatReloader
2024-03-30 14:08:08,569 DEBUG Using proactor: IocpProactor
2024-03-30 14:08:41,549 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:08:42,348 INFO Watching for file changes with StatReloader
2024-03-30 14:09:30,818 DEBUG Using proactor: IocpProactor
2024-03-30 14:10:55,447 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:10:56,562 INFO Watching for file changes with StatReloader
2024-03-30 14:11:15,115 DEBUG Using proactor: IocpProactor
2024-03-30 14:14:20,756 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:14:21,559 INFO Watching for file changes with StatReloader
2024-03-30 14:14:44,574 DEBUG Using proactor: IocpProactor
2024-03-30 14:16:38,771 DEBUG Using proactor: IocpProactor
2024-03-30 14:16:39,646 DEBUG Using proactor: IocpProactor
2024-03-30 14:16:40,201 DEBUG Using proactor: IocpProactor
2024-03-30 14:16:40,702 DEBUG Using proactor: IocpProactor
2024-03-30 14:22:30,877 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:22:31,662 INFO Watching for file changes with StatReloader
2024-03-30 14:22:57,997 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:22:58,789 INFO Watching for file changes with StatReloader
2024-03-30 14:23:29,162 DEBUG Using proactor: IocpProactor
2024-03-30 14:24:20,025 DEBUG Using proactor: IocpProactor
2024-03-30 14:24:29,556 DEBUG Using proactor: IocpProactor
2024-03-30 14:24:31,648 DEBUG Using proactor: IocpProactor
2024-03-30 14:24:40,766 DEBUG Using proactor: IocpProactor
2024-03-30 14:24:44,999 DEBUG Using proactor: IocpProactor
2024-03-30 14:24:49,493 DEBUG Using proactor: IocpProactor
2024-03-30 14:25:17,303 DEBUG Using proactor: IocpProactor
2024-03-30 14:27:00,175 DEBUG Using proactor: IocpProactor
2024-03-30 14:29:08,335 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:29:09,142 INFO Watching for file changes with StatReloader
2024-03-30 14:29:31,141 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 14:29:32,003 INFO Watching for file changes with StatReloader
2024-03-30 14:30:10,041 DEBUG Using proactor: IocpProactor
2024-03-30 15:05:22,163 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:05:23,086 INFO Watching for file changes with StatReloader
2024-03-30 15:05:25,537 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:05:26,426 INFO Watching for file changes with StatReloader
2024-03-30 15:06:03,891 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:06:04,671 INFO Watching for file changes with StatReloader
2024-03-30 15:06:32,908 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:06:34,014 INFO Watching for file changes with StatReloader
2024-03-30 15:06:45,306 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:06:46,149 INFO Watching for file changes with StatReloader
2024-03-30 15:07:05,557 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:07:06,525 INFO Watching for file changes with StatReloader
2024-03-30 15:07:16,750 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:07:17,633 INFO Watching for file changes with StatReloader
2024-03-30 15:07:24,597 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:07:25,507 INFO Watching for file changes with StatReloader
2024-03-30 15:07:53,277 DEBUG Using proactor: IocpProactor
2024-03-30 15:10:38,992 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:10:40,075 INFO Watching for file changes with StatReloader
2024-03-30 15:10:48,177 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:10:49,156 INFO Watching for file changes with StatReloader
2024-03-30 15:10:52,719 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:10:53,611 INFO Watching for file changes with StatReloader
2024-03-30 15:11:25,822 DEBUG Using proactor: IocpProactor
2024-03-30 15:12:28,355 DEBUG Using proactor: IocpProactor
2024-03-30 15:12:32,959 DEBUG Using proactor: IocpProactor
2024-03-30 15:12:36,951 DEBUG Using proactor: IocpProactor
2024-03-30 15:12:53,555 DEBUG Using proactor: IocpProactor
2024-03-30 15:12:57,979 DEBUG Using proactor: IocpProactor
2024-03-30 15:13:29,976 DEBUG Using proactor: IocpProactor
2024-03-30 15:13:42,240 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:13:42,950 INFO Watching for file changes with StatReloader
2024-03-30 15:15:30,250 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:15:31,105 INFO Watching for file changes with StatReloader
2024-03-30 15:16:07,668 DEBUG Using proactor: IocpProactor
2024-03-30 15:18:07,117 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:18:08,018 INFO Watching for file changes with StatReloader
2024-03-30 15:18:10,499 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:18:11,369 INFO Watching for file changes with StatReloader
2024-03-30 15:18:52,945 DEBUG Using proactor: IocpProactor
2024-03-30 15:20:31,036 ERROR Internal Server Error: /api/search/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\renderers.py", line 158, in render
    template_names = self.get_template_names(response, view)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\renderers.py", line 186, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Returned a template response with no `template_name` attribute set on either the view or response
2024-03-30 15:20:38,626 DEBUG Using proactor: IocpProactor
2024-03-30 15:20:52,301 DEBUG Using proactor: IocpProactor
2024-03-30 15:21:22,879 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 15:21:23,419 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 15:21:24,333 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 15:21:32,493 DEBUG Using proactor: IocpProactor
2024-03-30 15:21:51,196 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:21:52,145 INFO Watching for file changes with StatReloader
2024-03-30 15:22:39,147 DEBUG Using proactor: IocpProactor
2024-03-30 15:25:44,912 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:25:45,794 INFO Watching for file changes with StatReloader
2024-03-30 15:26:36,419 DEBUG Using proactor: IocpProactor
2024-03-30 15:33:08,899 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:33:10,298 INFO Watching for file changes with StatReloader
2024-03-30 15:34:10,474 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:34:11,371 INFO Watching for file changes with StatReloader
2024-03-30 15:34:35,235 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:34:36,112 INFO Watching for file changes with StatReloader
2024-03-30 15:34:38,380 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:34:39,627 INFO Watching for file changes with StatReloader
2024-03-30 15:37:56,416 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:37:57,267 INFO Watching for file changes with StatReloader
2024-03-30 15:38:14,136 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:38:14,935 INFO Watching for file changes with StatReloader
2024-03-30 15:38:21,894 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:38:22,785 INFO Watching for file changes with StatReloader
2024-03-30 15:39:29,803 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:39:30,568 INFO Watching for file changes with StatReloader
2024-03-30 15:40:04,395 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:40:05,263 INFO Watching for file changes with StatReloader
2024-03-30 15:40:10,058 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:40:11,023 INFO Watching for file changes with StatReloader
2024-03-30 15:41:08,052 DEBUG Using proactor: IocpProactor
2024-03-30 15:42:38,122 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:42:38,925 INFO Watching for file changes with StatReloader
2024-03-30 15:42:59,563 DEBUG Using proactor: IocpProactor
2024-03-30 15:44:59,095 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:44:59,930 INFO Watching for file changes with StatReloader
2024-03-30 15:45:27,160 DEBUG Using proactor: IocpProactor
2024-03-30 15:46:21,062 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:46:21,840 INFO Watching for file changes with StatReloader
2024-03-30 15:47:01,993 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:47:03,178 INFO Watching for file changes with StatReloader
2024-03-30 15:50:16,972 WARNING Not Found: /favicon.ico
2024-03-30 15:53:06,658 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:46,101 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:47,178 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:47,682 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:48,250 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:48,753 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:49,235 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:49,710 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:50,180 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:50,637 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:51,206 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:51,668 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:52,138 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:52,607 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:53,072 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:53,528 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:54,199 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:54,758 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:57,320 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:58,510 DEBUG Using proactor: IocpProactor
2024-03-30 15:54:59,438 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:00,476 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:01,512 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:03,408 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:04,215 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:04,819 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:05,644 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:06,393 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:07,334 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:45,710 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:46,275 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:46,795 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:47,410 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:47,934 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:48,462 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:48,964 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:49,496 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:49,990 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:50,488 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:51,025 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:51,552 DEBUG Using proactor: IocpProactor
2024-03-30 15:55:51,938 DEBUG Using proactor: IocpProactor
2024-03-30 15:56:08,313 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:56:10,157 INFO Watching for file changes with StatReloader
2024-03-30 15:56:34,580 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:56:35,491 INFO Watching for file changes with StatReloader
2024-03-30 15:57:11,678 DEBUG Using proactor: IocpProactor
2024-03-30 15:57:14,576 DEBUG Using proactor: IocpProactor
2024-03-30 15:57:15,524 DEBUG Using proactor: IocpProactor
2024-03-30 15:58:02,663 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 15:58:03,611 INFO Watching for file changes with StatReloader
2024-03-30 15:58:45,168 DEBUG Using proactor: IocpProactor
2024-03-30 16:00:29,834 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:00:30,708 INFO Watching for file changes with StatReloader
2024-03-30 16:00:48,062 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:00:49,018 INFO Watching for file changes with StatReloader
2024-03-30 16:01:02,782 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:01:03,843 INFO Watching for file changes with StatReloader
2024-03-30 16:01:54,418 DEBUG Using proactor: IocpProactor
2024-03-30 16:02:54,985 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:02:56,031 INFO Watching for file changes with StatReloader
2024-03-30 16:03:06,308 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:03:07,281 INFO Watching for file changes with StatReloader
2024-03-30 16:14:43,749 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:14:44,720 INFO Watching for file changes with StatReloader
2024-03-30 16:15:36,450 DEBUG Using proactor: IocpProactor
2024-03-30 16:17:34,718 DEBUG Using proactor: IocpProactor
2024-03-30 16:18:29,213 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:18:30,126 INFO Watching for file changes with StatReloader
2024-03-30 16:18:58,609 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:18:59,800 INFO Watching for file changes with StatReloader
2024-03-30 16:19:10,267 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:19:11,351 INFO Watching for file changes with StatReloader
2024-03-30 16:19:15,956 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:19:16,777 INFO Watching for file changes with StatReloader
2024-03-30 16:21:41,323 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:21:42,220 INFO Watching for file changes with StatReloader
2024-03-30 16:23:20,090 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:23:20,960 INFO Watching for file changes with StatReloader
2024-03-30 16:24:22,910 DEBUG Using proactor: IocpProactor
2024-03-30 16:24:28,170 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 16:24:29,068 INFO Watching for file changes with StatReloader
2024-03-30 16:24:40,628 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py changed, reloading.
2024-03-30 16:24:41,492 INFO Watching for file changes with StatReloader
2024-03-30 16:24:56,588 DEBUG Using proactor: IocpProactor
2024-03-30 16:24:58,509 DEBUG Using proactor: IocpProactor
2024-03-30 16:29:54,857 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\urls.py changed, reloading.
2024-03-30 16:29:55,784 INFO Watching for file changes with StatReloader
2024-03-30 16:37:21,437 ERROR Internal Server Error: /api/search/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\renderers.py", line 158, in render
    template_names = self.get_template_names(response, view)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\renderers.py", line 186, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Returned a template response with no `template_name` attribute set on either the view or response
2024-03-30 16:37:22,668 ERROR Internal Server Error: /api/search/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\renderers.py", line 158, in render
    template_names = self.get_template_names(response, view)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\rest_framework\renderers.py", line 186, in get_template_names
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Returned a template response with no `template_name` attribute set on either the view or response
2024-03-30 16:40:48,270 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:40:49,898 INFO Watching for file changes with StatReloader
2024-03-30 16:40:55,767 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:40:56,800 INFO Watching for file changes with StatReloader
2024-03-30 16:41:56,882 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 16:41:57,987 INFO Watching for file changes with StatReloader
2024-03-30 17:15:07,646 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:15:08,161 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:15:08,859 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:15:10,558 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:15:15,049 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:15:15,401 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:15:15,847 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:15:20,368 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:15:21,005 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:16:17,947 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:16:18,613 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:16:21,169 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:16:23,155 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:16:25,175 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:16:25,730 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:16:26,726 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:16:27,279 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:16:29,021 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-30 17:21:13,117 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-30 17:21:14,601 INFO Watching for file changes with StatReloader
