2024-03-28 00:18:57,221 INFO Watching for file changes with StatReloader
2024-03-28 00:19:04,246 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\monster\settings.py changed, reloading.
2024-03-28 00:19:10,124 INFO Watching for file changes with StatReloader
2024-03-28 00:21:05,399 WARNING Not Found: /images/placeholders/background.jpeg
2024-03-28 00:22:08,299 WARNING Not Found: /favicon.ico
2024-03-28 01:07:04,349 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-28 01:07:05,479 INFO Watching for file changes with StatReloader
2024-03-28 01:09:47,047 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-28 01:09:48,043 INFO Watching for file changes with StatReloader
2024-03-28 01:10:36,609 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-28 01:10:37,580 INFO Watching for file changes with StatReloader
2024-03-28 01:11:14,546 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-28 01:11:15,746 INFO Watching for file changes with StatReloader
2024-03-28 01:13:44,611 INFO C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\models.py changed, reloading.
2024-03-28 01:13:45,610 INFO Watching for file changes with StatReloader
2024-03-28 01:15:36,165 ERROR Internal Server Error: /manga/oyasumi-punpun/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 67, in manga_page
    return render(request, 'manga.html', context={'manga':manga})
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\defaulttags.py", line 197, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
2024-03-28 01:38:25,854 ERROR Internal Server Error: /manga/oyasumi-punpun/
Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\monster\manga\views.py", line 67, in manga_page
    return render(request, 'manga.html', context={'manga':manga})
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "c:\Users\Shamrock\Desktop\mangalib_monster обход блокировки ботов\.venv\lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 168: 'static', expected 'endblock'. Did you forget to register or load this tag?
